name: Ping scraper

on: 
  schedule:
    - cron: '11 * * * *'

jobs: 
  build:
    name: Keep-alive Heroku
    runs-on: ubuntu-latest
    env: 
      TEST: health
    steps:
      - name: Curl health endpoint
        run: 'curl "https://cumulus-data--scraper.herokuapp.com/$TEST"'